### ISSUE TITLE
Does not run examples

### ISSUE THREAD

**Issue by Retanaar** [mainfraame/cucumber-jest#1]
Hi,

when I try to run your examples with yarn test I got 
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'C:workcucumber-jestexample est
                                                                           eaturesscenario.feature'

       5 |     And the lastName text input value is Dean
       6 |     And the email text input value is james.dean@gmail.com
    >  7 |     And the password text input value is itsASecretShh...

**Comment by mainfraame** [comment]
Can you give me some more detail on how you are running the example?  

1 - Are you cd’ing into the example folder 
2 - running yarn install
3 - running yarn test?

Also, I'm assuming you're using a windows machine?

**Comment by mainfraame** [comment]
@Retanaar are you using a windows machine? I did all my development on a mac.  

I added support for windows pathing in v0.1.0, but because I have a mac I cannot test this.  Can someone with a windows machine verify this fix?

**Comment by mainfraame** [comment]
@Retanaar since you didn't respond, I'm going to close this out. If you are still getting the error, feel free to open up another issue.
