### ISSUE TITLE
Is it possible to generate snippets for new step definitions?

### ISSUE THREAD

**Issue by themathmagician** [mainfraame/cucumber-jest#11]
Given I have a line in my feature file that is not implemented
When I run jest
Then I would like to see generated snippets

**Comment by mainfraame** [comment]
the latest version should log out an error if it cannot find a step definition for text in your feature file. 

Are you are looking to have the same feature as cucumber-js, where you can print out all available steps without executing?

**Comment by themathmagician** [comment]
Yes, other cucumber implementations print step definitions as part of the error message, so you dont have to write boilerplate code.

**Comment by patricksmms** [comment]
@themathmagician I think [this](https://github.com/mainfraame/cucumber-jest/pull/12) is what you are looking for.

**Comment by themathmagician** [comment]
Yes, exactly 🤩

**Comment by mainfraame** [comment]
@patricksmms thanks for helping!  @themathmagician I'll merge this in now and run a build and publish it tonight (v0.2.4)

**Comment by mainfraame** [comment]
@themathmagician feature request is available / published (0.2.4)

**Comment by themathmagician** [comment]
Thanks, verified, working :)
