### ISSUE TITLE
Usage of World for tests written in Javascript ?

### ISSUE THREAD

**Issue by themathmagician** [mainfraame/cucumber-jest#13]
Hi there

I am trying to introduce BDD to a Nuxt.js project, and I started by implementing a simple smoke test, using Javascript in an example Nuxt.js project. 
I have seen in your documentation, that the `World` object should be used, to carry state between steps.

My feature file looks like this:
```
Feature: I verify main functionality after deployment of application
  As a product owner
  I want to make sure
  That nothing is wrong with the latest deployment.

  @smoke
  Scenario: I can see a page at my application URL
    Given I visit the URL 'https://www.mathmagicians.dk'
    Then I can see content
    And the http status code is 200
```
My test implementation is as follows:
```
import {Given, When, Then, setWorldConstructor} from "@cucumber/cucumber"

const axios = require('axios')

let CustomWorld = function () {
  this.response = {}
}

setWorldConstructor(CustomWorld)

Given("I visit the URL {string}", async function (url) {
  const strippedUrl = url.replace(/['"]+/g, '')
  console.log("url is", url, strippedUrl)

  this.response = await axios.get(strippedUrl)
    .then(r => {
      console.log("called with", r, url)
      expect(r.data).toBeDefined()
    })
})

Then("I can see content", function () {
  console.log( "second step response is ", this.response )
  expect(this.response.data.results.length).toBeGreaterThan(0)
})

Then("the http status code is {int}", function (expectedStatus) {
  expect(this.response.status).toBe(expectedStatus)
})
```
Here is a link to [my code repo](https://github.com/Mathmagicians/nuxt-bdd-example).

Unfortunately, `this.response` is undefined in the second and third step.
So my question is, how can I inject my Custom world in a Javascript project?

Best
Agata

**Comment by kevincmanning** [comment]
Problem is not your world or world constructor. The problem is the way you constructed your "Given" as well as a couple other issues (response.data.results) is not expected to exist. response.data is a string

Other issue was below, axios is returning a number,  but the argument accepted by the Then step was a string.
Tested this locally and it works

Hope this helps

```
Given("I visit the URL {string}", async function (url) {
  const strippedUrl = url.replace(/['"]+/g, '')
  console.log("url is", url, strippedUrl)

  this.response = await axiosClient.get(strippedUrl);
  expect(this.response.data).toBeDefined();
})

Then("I can see content", function () {
  console.log("second step response is ", this.response)
  expect(this.response.data.length).toBeGreaterThan(0)
})

Then("the http status code is {int}", function (expectedStatus) {
  expect(this.response.status).toBe(Number(expectedStatus))
})
```

**Comment by themathmagician** [comment]
Thanks man 😀! Yup, [it works](https://github.com/Mathmagicians/nuxt-bdd-example/runs/2269207706?check_suite_focus=true) ... I see...  note to self, don't use `this` and arrow functions.

I have 2 cents worth of thoughts left:

1.
According to the [Cucumber docs](https://cucumber.io/docs/cucumber/cucumber-expressions/), the cucumber expression should match a string - stripped of quotiation marks, and then I would expect the injected parameter to be the match.

2. 
Maybe it is worth updating the docs with a ECMA example (as well as Typescript). Are you guys accepting pull requests?

**Comment by kevincmanning** [comment]
@mainfraame can answer that better than I can. I just got an email because I am "watching" the repo and responded 😆

**Comment by mainfraame** [comment]
Thanks for helping out, @kevincmanning.

@themathmagician I believe all examples are already written in typescript. If you want to contribute by updating the docs, feel free to open a PR.
