### ISSUE TITLE
expressions evaluation behaves unexpectedly 

### ISSUE THREAD

**Issue by zanona** [mainfraame/cucumber-jest#14]
First, I would like to thank you for the initiative on keeping the same development experience between the cucumber test runner and jest as I believe this brings the best of both worlds.

Now, whenever using two variables _(or more)_ in the same sentence with `{string} and {string}` the first one is repeated as the second where the first one passed wrapped in quotes?

```cucumber
# test.feature
Feature:
    Scenario:
	When I say "foo" and "bar"
```

The test below passes but should fail as bar is expected to be `bar` and foo is expected to be `foo` and not `"foo"`

```js
// test.steps.js
const { When } = require('@cucumber/cucumber');

When('I say {string} and {string}', function (foo, bar) {
    expect(bar).toBe('foo'); // bar should be bar
    expect(foo).toBe('"foo"'); // foo shouldn't be wrapped in quotes
});
```
When changing the test above to `{word} and {string}` the variables are both passed correctly, although, still wrapped in quotes?

```js
// test.steps.js
When('I say {word} and {string}', function (foo, bar) {
    expect(bar).toBe('"bar"'); // bar shouldn't be wrapped in quotes
    expect(foo).toBe('"foo"'); // foo shouldn't be wrapped in quotes
});

```

Perhaps [@cucumber/cucumber-expressions](https://www.npmjs.com/package/@cucumber/cucumber-expressions) could facilitate this integration?

_Another test case to investigate_
```js
// When I say "foo" and "bar" and "baz"
When('I say {string} and {string} and {string}', function (foo, bar, baz) {
    console.log(foo, bar, baz); // "foo" foo undefined
});
```

**Comment by kevincmanning** [comment]
Interestingly, the step definition was already being parsed to type CucumberExpression (which I saw inside of @cucumber/cucumber-expressions). I looked at the code in that project's tests and replicated it.

For strings, it does indeed strip the quotes, but for words, it seems that it includes them. I double checked the documentation, and it seems that that is expected.

**Comment by zanona** [comment]
Thank you for following up so quickly.

>  I double checked the documentation, and it seems that that is expected.

Interesting, that's surprising since `cucumber-js` does strip quotes from both `{word}` and `{string}`.
I've noticed cucumber documentation is still somewhat lacking in a way, at least for the npm modules.

**Comment by kevincmanning** [comment]
@zanona 

Anytime. I'm not really a maintainer or anything, just like the project and want to contribute.

I wonder if there are just some inconsistencies among implementations.

The documentation I was looking at in particular was here:
https://cucumber.io/docs/cucumber/cucumber-expressions/#parameter-types

For {string}, it is pretty explicit that the quotes should be removed, but {word} doesn't really specify. I just went with what the CucumberExpression object returned me. Presumably that is generated from somewhere in the cucumber project code, but I didn't dig that deep into it.

I'll check it out tonight, because while I have my PR open, it's worth investigating the discrepancy.

**Comment by zanona** [comment]
Hi, @kevincmanning, just a heads-up after testing the behaviour on `cucumber-js` and,  indeed, it follows your assumption. 

- `{string}` strips quotes: `Given I say "foo"` < `Given("I say {string}, (w => assert(w, "foo")))`
- `{word}` preserves quotes : `Given I say "foo"` < `Given("I say {word}, (w => assert(w, "\"foo\"")))`

So, I believe the `{word}` expression is for cases where we don't need to wrap a term in quotes.
like:  `Given I say foo` < `Given("I say {word}, (w => assert(w, "foo")))`

**Comment by kevincmanning** [comment]
Thanks @zanona for confirming. That helps a lot.

**Comment by zanona** [comment]
Thanks so much for implementing this, @kevincmanning 👏
