### ISSUE TITLE
Having trouble setting up

### ISSUE THREAD

**Issue by catharsisjelly** [mainfraame/cucumber-jest#16]
Hiya,

I've been trying to implement this module into a project and been having a great deal of difficulty. Whenever I run jest I just get an error telling me there is an `unexpected token` 

```
/home/chris/code/myApi/tests/feature/world.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { setWorldConstructor } from '@cucumber/cucumber';
```

I know this might be a `jest` config problem but I have followed your example with no results. Any  help would be appreciated and maybe it's something I can contribute back into the documentation to help others in the future. I've included relevant files below if it's helpful.

```
tests
├── feature
│   ├── hooks.tsx
│   ├── specs
│   │   └── categories
│   │       └── get.feature
│   ├── steps
│   │   └── steps.ts
│   └── world.ts
```

## world.ts

```typescript
import { setWorldConstructor } from '@cucumber/cucumber';

export class TestWorld {
}

setWorldConstructor(TestWorld);
```

## hooks.ts

```typescript
import { BeforeAll, AfterAll } from '@cucumber/cucumber';
import { TestWorld } from './world';

BeforeAll(async function (this: TestWorld) {
});

AfterAll(async function (this: TestWorld) {
});

```

## jest.config.json

```json
module.exports = {
  preset: 'ts-jest',
  moduleFileExtensions: [
    "feature",
    "ts",
    "js",
    "json",
    "tsx"
  ],
  setupFilesAfterEnv: [
    "<rootDir>/node_modules/cucumber-jest/dist/init.js",
    "<rootDir>/tests/feature/world.ts",
    "<rootDir>/tests/feature/hooks.tsx",
    "<rootDir>/tests/feature/steps/steps.ts"
  ],
  testEnvironment: 'node',
  testMatch: [
    "<rootDir>/tests/feature/**/*.feature"
  ],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": "babel-jest",
    "^.+\\.(feature)$": "cucumber-jest"
  },
  verbose: true
};
```

## get.feature

```cucumber
Feature: Get a stored Category by ID

    Background: Stored Categories can be retrieved
        Given I do something

        Scenario: Return Category object
            When I make the request
            Then the response should have a statusCode of 200
```

**Comment by mainfraame** [comment]
@catharsisjelly it looks like it's not transpiling your code from ESM (ecma script modules) to CommonJS. Have you tried running it without the **preset:ts-node**? If that doesn't work, can you share your **Babel.config.js**?

**Comment by catharsisjelly** [comment]
Thanks so much for responding, I really appreciate it - I removed `preset: 'ts-jest'` from the `jest.config.js` and got the same error. I don't actually have a `babel.config.js` file

**Comment by mainfraame** [comment]
Got it. So the unexpected token is most likely related to the import statement. It looks like from ts-jest docs that you are not required to add the babel-jest transformer in your jest.config.js. Put back the preset line with ts-jest and then remove the line u have in transformers for babel-jest.


From what I'm gathering, the preset itself will define the transformers for you.

**Comment by catharsisjelly** [comment]
Booyah, that worked (I think) it's at least now demanding that I start to write some bits in the Steps which is a great thing. Is there anything I can contribute towards the docs to perhaps prevent other people from having similar issues?

**Comment by mainfraame** [comment]
Glad to hear it worked out for you. I'm not against updating the docs if you think it would be helpful. PRs are always welcome.
