### ISSUE TITLE
Reporting and parallel run

### ISSUE THREAD

**Issue by mandeep1987** [mainfraame/cucumber-jest#17]
Is there a possibility to have 
a. allure reporting integrated with this framework?
b. How to run test cases in parallel?

**Comment by mainfraame** [comment]
cucumber-jest isn’t a framework, it’s a transformer for jest. So any reporter that’s available for jest will work with cucumber-jest. 

If you want to add allure reporter, you should look for a jest allure reporter like this one: https://www.npmjs.com/package/jest-allure. Try searching npmjs.org; there are quite a few available. They should have instructions on how to configure them. 

As far as parallel execution goes, as long as you’re not running the jest cli with the “—runInBand” flag, it should be executing in parallel. You can adjust how many parallel instances are used with the “—maxWorkers” flag.

https://jestjs.io/docs/cli#--maxworkersnumstring

https://jestjs.io/docs/cli#--runinband

**Comment by mandeep1987** [comment]
Thanks let me check it out.

**Comment by mainfraame** [comment]
closing this
