### ISSUE TITLE
World object doesn't persist across files in javastript test

### ISSUE THREAD

**Issue by Narmical** [mainfraame/cucumber-jest#18]
I set up my test suite like you recommended by separating the work, hooks and steps files. However any context I add to the this object in the steps, is lost by the time it gets round to the hooks. 

Similarly if i make more than one steps file and distribute my steps between them, any state set in one file isn't available in the world object in the other file.

I'm hoping this is user error, but any thoughts?

**Comment by mainfraame** [comment]
To clarify, you’re trying to set context in a step and do something with that inside of a hook?  Can you be specific about which hook?

**Comment by Narmical** [comment]
Yes that is exactly what I'm trying to do.

I have a step that renders a react page at store it in this.renderedPage. I have an after hook in the hooks file and i want to print out the state of the page using this.renderedPage.debug();

If i move the after hook into the steps file, the context is there and this.renderedPage.debug() works

**Comment by mainfraame** [comment]
Would you mind posting snippets of your code? I don’t need to see everything in the hooks and steps, just the rendering part of your step and the debug call for afterAll/afterEach...

**Comment by Narmical** [comment]
```
After(async (info) => {
  this.renderedPage.debug();
  cleanup();
});
```

```
Given(/^my step matcher$/, () => {
 ...
  this.renderedPage = render(<Router />,
    {
      initialState: {
        userProgress: this.userProgress,
        nav,
        schedule: this.schedule
      }
    });
});
```

I strongly suspect there is nothing wrong with this code, per se. As when they are both in the same file it works perfectly. However when I separate them into the hooks and steps files, as suggested, `this` is different between the two.

Same for if I put my steps is multiple files, suddenly they don't have the same this object, when they did so before.

**Comment by mainfraame** [comment]
@Narmical sorry for the super late response. i just started a new job and got engaged; so, I've been busy.

The reason why it's not working is because you are using [Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). Arrow functions do not create a closure, so any use of **_this_** will not be set on the world object. In order for that to work, you have to use classic functions:

```
After(async function (info) {
  this.renderedPage.debug();
  cleanup();
});
```

```
Given(/^my step matcher$/, function() {
  this.renderedPage = render(<Router />,
    {
      initialState: {
        userProgress: this.userProgress,
        nav,
        schedule: this.schedule
      }
    });
});
```
