### ISSUE TITLE
Scenarios Without Tags Run When a Tag is Specified

### ISSUE THREAD

**Issue by atiernan** [mainfraame/cucumber-jest#20]
```
Feature: Example Feature

  Scenario: This should not be ran
    Then assert false

  @exampleTag
  Scenario: This should be ran
    Then assert true
```

### What do you expect to happen:
Running `TAGS=exampleTag jest`, only the scenario with the @exampleTag should be tested.

### What actually happens
Both scenarios are tested

I think this is due to the `!!tags.length` test in [src/parsers/suite:111](https://github.com/mainfraame/cucumber-jest/blob/7bf4ca4a899ef4aa248a7852834940edd81ed721/src/parsers/suite.ts#L111). As the scenario doesn't have a tag, this returns `false`, which means the `skip` variable contains `false`, and the scenario is included. 
The work around I've found is adding a dummy tag to every scenario

**Comment by mainfraame** [comment]
@atiernan sorry for the delayed response, i just started a new job and haven't had time to look into this. It looks like your assumption is correct. i'll push a patch here within an hour and notify you when it's available.

**Comment by mainfraame** [comment]
@atiernan 0.3.1 has been published with the fix in it. thanks for looking into the issue

**Comment by atiernan** [comment]
This now runs all tagged scenarios whenever any tag is provided.

```
Feature: Example Feature

  Scenario: This should not be ran
    Then assert false

  @shouldRun
  Scenario: This should be ran
    Then assert true

  @shouldNotRun
  Scenario: This should be ran
    Then assert false
```
Running `TAGS=shouldRun jest` runs @shouldRun and @shouldNotRun tagged scenarios but not the untagged scenario
