### ISSUE TITLE
Is it a must to install react-dom? I want to run it for all my node.js test only.

### ISSUE THREAD

**Issue by tom10271** [mainfraame/cucumber-jest#22]
FAIL  tests/features/sales-orders/basic.feature
  ● Test suite failed to run

    Cannot find module 'react' from 'node_modules/react-dom/cjs/react-dom-test-utils.development.js'

    Require stack:
      node_modules/react-dom/cjs/react-dom-test-utils.development.js
      node_modules/react-dom/test-utils.js
      node_modules/cucumber-jest/dist/exec.js
      tests/features/sales-orders/basic.feature

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:17:13
      at Object.<anonymous> (node_modules/react-dom/cjs/react-dom-test-utils.development.js:2117:5)

**Comment by mainfraame** [comment]
@tom10271 sorry for the delayed response. This can sometimes be the result of having two different versions of react and react-dom. Could you provide me with your react and react-dom dependencies in your package.json?

**Comment by mainfraame** [comment]
@tom10271 I'm adding a check to see if react exists before trying to require react-dom. This should most likely resolve your issue and anyone else who is not using react.

**Comment by mainfraame** [comment]
@tom10271 0.3.1 is published with react-dom as an optional dependency. let me know if you still have issues.
