### ISSUE TITLE
 has no exported member 'And'

### ISSUE THREAD

**Issue by pdashford** [mainfraame/cucumber-jest#4]
Stating that it support 'And' however when adding `And` into the Import 

import { Given, Then, When, And } from 'cucumber'

/@types/cucumber\"' has no exported member 'And'.",
	"source": "ts",
	"startLineNumber": 18,
	"startColumn": 29,
	"endLineNumber": 18,
	"endColumn": 32
}

**Comment by mainfraame** [comment]
@pdashford ”And” isn’t an import from cucumber. It’s an alias only used in gherkin that can match either a Given, When, or Then step.

Also, if you look at cucumbers code, Given, When, and Then are also aliases for defineStep. In other words, those three imports are just aliases for the same function you use to define a step. 

Let me know if this helps.

**Comment by pdashford** [comment]
Yes thats fine, I changed my feature `And` to `Then`

**Comment by mainfraame** [comment]
@pdashford you don't have to do that, you can use "And" for any of the "Given", "When", or "Then" steps. Take a look at these two files:

https://github.com/mainfraame/cucumber-jest/blob/master/example/test/features/scenario.feature#L5
https://github.com/mainfraame/cucumber-jest/blob/master/example/test/steps.ts#L17

As you can see, I am using an "And" for a "When" step. The purpose of "And" is for readability; to break up Given/When/Then.
Cucumber's documentation talks about this for "And" and "But":

https://cucumber.io/docs/gherkin/reference/#and-but

**Comment by mainfraame** [comment]
@pdashford you don't have to do that, you can use "And" for any of the "Given", "When", or "Then" steps. Take a look at these two files:

https://github.com/mainfraame/cucumber-jest/blob/master/example/test/features/scenario.feature#L5
https://github.com/mainfraame/cucumber-jest/blob/master/example/test/steps.ts#L17

As you can see, I am using an "And" for a "When" step. The purpose of "And" is for readability; to break up Given/When/Then.
Cucumber's documentation talks about this for "And" and "But":

https://cucumber.io/docs/gherkin/reference/#and-but

**Comment by mainfraame** [comment]
@pdashford you don't have to do that, you can use "And" for any of the "Given", "When", or "Then" steps. Take a look at these two files:

https://github.com/mainfraame/cucumber-jest/blob/master/example/test/features/scenario.feature#L5
https://github.com/mainfraame/cucumber-jest/blob/master/example/test/steps.ts#L17

As you can see, I am using an "And" for a "When" step. The purpose of "And" is for readability; to break up Given/When/Then.
Cucumber's documentation talks about this for "And" and "But":

https://cucumber.io/docs/gherkin/reference/#and-but
